import json
import os


INPUT_FILE = "output/engineering_diagnosis.json"
OUTPUT_FILE = "output/prioritized_diagnosis.json"


# ---------------------------------------------------------
# Load diagnosis
# ---------------------------------------------------------

def load_diagnosis():
    """
    Load engineering diagnoses generated by
    engineering_diagnosis.py.
    """

    if not os.path.exists(INPUT_FILE):
        raise FileNotFoundError(
            f"Engineering diagnosis not found: {INPUT_FILE}"
        )

    with open(
        INPUT_FILE,
        "r",
        encoding="utf-8"
    ) as file:
        return json.load(file)


# ---------------------------------------------------------
# Diagnosis relationships
# ---------------------------------------------------------

def are_related(diagnosis_a, diagnosis_b):
    """
    Determine whether two diagnoses describe
    substantially related spectral behavior.
    """

    issue_a = diagnosis_a["issue"]
    issue_b = diagnosis_b["issue"]

    related_pairs = {
        (
            "low_frequency_distribution_imbalance",
            "lower_mid_spectral_concentration"
        ),
        (
            "lower_mid_spectral_concentration",
            "low_frequency_distribution_imbalance"
        )
    }

    return (
        issue_a,
        issue_b
    ) in related_pairs


# ---------------------------------------------------------
# Severity ranking
# ---------------------------------------------------------

def severity_score(severity):
    """
    Convert severity into a numerical priority score.
    """

    scores = {
        "low": 1,
        "moderate": 2,
        "high": 3,
        "critical": 4
    }

    return scores.get(
        severity,
        0
    )


# ---------------------------------------------------------
# Select primary diagnosis
# ---------------------------------------------------------

def select_primary_diagnosis(diagnoses):
    """
    Select the strongest diagnosis using severity
    and confidence.
    """

    if not diagnoses:
        return None

    confidence_scores = {
        "low": 1,
        "moderate": 2,
        "high": 3
    }

    def ranking(diagnosis):

        severity = severity_score(
            diagnosis.get(
                "severity",
                "low"
            )
        )

        confidence = confidence_scores.get(
            diagnosis.get(
                "confidence",
                "low"
            ),
            0
        )

        return (
            severity,
            confidence
        )

    return max(
        diagnoses,
        key=ranking
    )


# ---------------------------------------------------------
# Consolidate related diagnoses
# ---------------------------------------------------------

def consolidate_diagnoses(diagnoses):
    """
    Group related diagnoses into a single dominant
    engineering issue while preserving supporting evidence.
    """

    if not diagnoses:
        return []

    consolidated = []

    used_indexes = set()

    for index, diagnosis in enumerate(
        diagnoses
    ):

        if index in used_indexes:
            continue

        related = [
            (
                related_index,
                other
            )
            for related_index, other
            in enumerate(diagnoses)
            if (
                related_index != index
                and related_index not in used_indexes
                and are_related(
                    diagnosis,
                    other
                )
            )
        ]

        if not related:

            consolidated.append(
                {
                    "primary_diagnosis": diagnosis,
                    "supporting_diagnoses": []
                }
            )

            used_indexes.add(index)

            continue

        group = [
            diagnosis
        ]

        group_indexes = [
            index
        ]

        for related_index, other in related:

            group.append(other)
            group_indexes.append(
                related_index
            )

        primary = select_primary_diagnosis(
            group
        )

        supporting = [
            item
            for item in group
            if item is not primary
        ]

        consolidated.append(
            {
                "primary_diagnosis": primary,
                "supporting_diagnoses": supporting
            }
        )

        used_indexes.update(
            group_indexes
        )

    return consolidated


# ---------------------------------------------------------
# Prioritize consolidated groups
# ---------------------------------------------------------

def prioritize_groups(groups):
    """
    Rank consolidated diagnosis groups by the
    severity and confidence of their primary diagnosis.
    """

    confidence_scores = {
        "low": 1,
        "moderate": 2,
        "high": 3
    }

    def ranking(group):

        diagnosis = group["primary_diagnosis"]

        severity = severity_score(
            diagnosis.get(
                "severity",
                "low"
            )
        )

        confidence = confidence_scores.get(
            diagnosis.get(
                "confidence",
                "low"
            ),
            0
        )

        return (
            severity,
            confidence
        )

    return sorted(
        groups,
        key=ranking,
        reverse=True
    )


# ---------------------------------------------------------
# Build final result
# ---------------------------------------------------------

def build_prioritized_diagnosis(
    diagnosis_report
):
    """
    Build the prioritized and consolidated
    engineering diagnosis.
    """

    diagnoses = diagnosis_report.get(
        "diagnoses",
        []
    )

    groups = consolidate_diagnoses(
        diagnoses
    )

    groups = prioritize_groups(
        groups
    )

    prioritized = []

    for index, group in enumerate(
        groups,
        start=1
    ):

        primary = group[
            "primary_diagnosis"
        ]

        supporting = group[
            "supporting_diagnoses"
        ]

        priority = "secondary"

        if index == 1:
            priority = "primary"

        prioritized.append(
            {
                "priority": priority,
                "primary_diagnosis": primary,
                "supporting_diagnoses": supporting
            }
        )

    return prioritized


# ---------------------------------------------------------
# Save result
# ---------------------------------------------------------

def save_prioritized_diagnosis(
    diagnosis_report,
    prioritized
):
    """
    Save the prioritized diagnosis report.
    """

    output = {
        "file": diagnosis_report["file"],
        "reference_count": (
            diagnosis_report["reference_count"]
        ),
        "measurement_type": (
            diagnosis_report["measurement_type"]
        ),
        "diagnosis_count": len(
            diagnosis_report.get(
                "diagnoses",
                []
            )
        ),
        "prioritized_groups": prioritized
    }

    with open(
        OUTPUT_FILE,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            output,
            file,
            indent=4
        )


# ---------------------------------------------------------
# Display result
# ---------------------------------------------------------

def print_prioritized_diagnosis(
    diagnosis_report,
    prioritized
):
    """
    Display the prioritized diagnosis in the terminal.
    """

    print()
    print("========================================")
    print("PRIORITIZED ENGINEERING DIAGNOSIS")
    print("========================================")
    print()

    print(
        f"Target mix: {diagnosis_report['file']}"
    )

    print()

    if not prioritized:

        print(
            "No diagnoses available."
        )

        print()

        return

    for index, group in enumerate(
        prioritized,
        start=1
    ):

        primary = group[
            "primary_diagnosis"
        ]

        supporting = group[
            "supporting_diagnoses"
        ]

        print(
            f"PRIORITY {index}: "
            f"{group['priority'].upper()}"
        )

        print(
            f"Issue: "
            f"{primary['issue']}"
        )

        print(
            f"Severity: "
            f"{primary['severity']}"
        )

        print(
            f"Confidence: "
            f"{primary['confidence']}"
        )

        print()

        print(
            "Diagnosis:"
        )

        print(
            f"  {primary['diagnosis']}"
        )

        if supporting:

            print()

            print(
                "Supporting diagnosis:"
            )

            for diagnosis in supporting:

                print(
                    f"  - {diagnosis['issue']}"
                )

        print()
        print("----------------------------------------")
        print()


# ---------------------------------------------------------
# Main
# ---------------------------------------------------------

def main():

    diagnosis_report = (
        load_diagnosis()
    )

    prioritized = (
        build_prioritized_diagnosis(
            diagnosis_report
        )
    )

    save_prioritized_diagnosis(
        diagnosis_report,
        prioritized
    )

    print_prioritized_diagnosis(
        diagnosis_report,
        prioritized
    )

    print(
        "Prioritized diagnosis saved to:"
    )

    print(
        OUTPUT_FILE
    )

    print()


if __name__ == "__main__":
    main()