import json
import os


INPUT_FILE = "output/deviation_report.json"
OUTPUT_FILE = "output/engineering_diagnosis.json"


def load_deviation_report():
    """
    Load the deviation report generated by
    deviation_detector.py.
    """

    if not os.path.exists(INPUT_FILE):
        raise FileNotFoundError(
            f"Deviation report not found: {INPUT_FILE}"
        )

    with open(
        INPUT_FILE,
        "r",
        encoding="utf-8"
    ) as file:
        return json.load(file)


def get_band(deviations, band):
    """
    Return the deviation information for one band.
    """

    return deviations.get(band, {})


def is_above(
    deviations,
    band,
    minimum_z
):
    """
    Check whether a band is above the reference
    by at least the specified z-score.
    """

    result = get_band(
        deviations,
        band
    )

    return (
        result.get("z_score", 0) >= minimum_z
    )


def is_below(
    deviations,
    band,
    minimum_z
):
    """
    Check whether a band is below the reference
    by at least the specified z-score.
    """

    result = get_band(
        deviations,
        band
    )

    return (
        result.get("z_score", 0) <= -minimum_z
    )


def get_classification(
    deviations,
    band
):
    """
    Get the statistical classification for a band.
    """

    return get_band(
        deviations,
        band
    ).get(
        "classification",
        "unknown"
    )


def diagnose_low_frequency_imbalance(
    deviations
):
    """
    Detect a pattern where sub and bass are below
    reference while low-mid energy is elevated.
    """

    sub_low = is_below(
        deviations,
        "sub",
        1.0
    )

    bass_low = is_below(
        deviations,
        "bass",
        1.0
    )

    low_mid_high = is_above(
        deviations,
        "low_mid",
        1.0
    )

    if (
        sub_low
        and bass_low
        and low_mid_high
    ):

        severity = "moderate"

        if is_above(
            deviations,
            "low_mid",
            2.0
        ):
            severity = "high"

        return {
            "issue": (
                "low_frequency_distribution_imbalance"
            ),
            "severity": severity,
            "evidence": [
                (
                    "Sub energy is below the "
                    "reference range."
                ),
                (
                    "Bass energy is below the "
                    "reference range."
                ),
                (
                    "Low-mid energy is above the "
                    "reference range."
                )
            ],
            "diagnosis": (
                "Low-frequency spectral energy appears "
                "to be disproportionately concentrated "
                "in the low-mid region relative to the "
                "reference profile."
            ),
            "confidence": "high"
        }

    return None


def diagnose_high_mid_concentration(
    deviations
):
    """
    Detect elevated low-mid and mid energy together.
    """

    low_mid_high = is_above(
        deviations,
        "low_mid",
        1.0
    )

    mid_high = is_above(
        deviations,
        "mid",
        1.0
    )

    if (
        low_mid_high
        and mid_high
    ):

        severity = "moderate"

        if (
            is_above(
                deviations,
                "low_mid",
                2.0
            )
            and is_above(
                deviations,
                "mid",
                1.0
            )
        ):
            severity = "high"

        return {
            "issue": (
                "lower_mid_spectral_concentration"
            ),
            "severity": severity,
            "evidence": [
                (
                    "Low-mid energy is above "
                    "the reference range."
                ),
                (
                    "Mid energy is above "
                    "the reference range."
                )
            ],
            "diagnosis": (
                "Spectral energy is concentrated more "
                "strongly in the lower and middle "
                "frequency regions than in the "
                "reference profile."
            ),
            "confidence": "high"
        }

    return None


def diagnose_reduced_high_frequency_energy(
    deviations
):
    """
    Detect reduced presence and brilliance energy.
    """

    presence_low = is_below(
        deviations,
        "presence",
        1.0
    )

    brilliance_low = is_below(
        deviations,
        "brilliance",
        1.0
    )

    if (
        presence_low
        and brilliance_low
    ):

        severity = "moderate"

        if (
            is_below(
                deviations,
                "presence",
                2.0
            )
            or is_below(
                deviations,
                "brilliance",
                2.0
            )
        ):
            severity = "high"

        return {
            "issue": (
                "reduced_high_frequency_energy"
            ),
            "severity": severity,
            "evidence": [
                (
                    "Presence energy is below "
                    "the reference range."
                ),
                (
                    "Brilliance energy is below "
                    "the reference range."
                )
            ],
            "diagnosis": (
                "Energy in the presence and brilliance "
                "regions is reduced relative to the "
                "reference profile."
            ),
            "confidence": "moderate"
        }

    return None


def run_diagnostics(
    deviation_report
):
    """
    Run all engineering diagnosis rules.
    """

    deviations = deviation_report["bands"]

    diagnoses = []

    diagnosis = diagnose_low_frequency_imbalance(
        deviations
    )

    if diagnosis:
        diagnoses.append(
            diagnosis
        )

    diagnosis = diagnose_high_mid_concentration(
        deviations
    )

    if diagnosis:
        diagnoses.append(
            diagnosis
        )

    diagnosis = diagnose_reduced_high_frequency_energy(
        deviations
    )

    if diagnosis:
        diagnoses.append(
            diagnosis
        )

    return diagnoses


def save_diagnosis(
    deviation_report,
    diagnoses
):
    """
    Save engineering diagnosis results.
    """

    output = {
        "file": deviation_report["file"],
        "reference_count": (
            deviation_report["reference_count"]
        ),
        "measurement_type": (
            deviation_report["measurement_type"]
        ),
        "diagnoses": diagnoses
    }

    with open(
        OUTPUT_FILE,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            output,
            file,
            indent=4
        )


def print_diagnosis(
    deviation_report,
    diagnoses
):
    """
    Display engineering diagnoses in the terminal.
    """

    print()
    print("========================================")
    print("ENGINEERING DIAGNOSIS")
    print("========================================")
    print()

    print(
        f"Target mix: {deviation_report['file']}"
    )

    print()

    if not diagnoses:

        print(
            "No diagnostic patterns detected."
        )

        print()

        return

    for index, diagnosis in enumerate(
        diagnoses,
        start=1
    ):

        print(
            f"DIAGNOSIS {index}"
        )

        print(
            f"Issue: "
            f"{diagnosis['issue']}"
        )

        print(
            f"Severity: "
            f"{diagnosis['severity']}"
        )

        print(
            f"Confidence: "
            f"{diagnosis['confidence']}"
        )

        print()

        print("Evidence:")

        for evidence in (
            diagnosis["evidence"]
        ):
            print(
                f"  - {evidence}"
            )

        print()

        print("Diagnosis:")

        print(
            f"  {diagnosis['diagnosis']}"
        )

        print()

    print("========================================")


def main():

    deviation_report = (
        load_deviation_report()
    )

    diagnoses = run_diagnostics(
        deviation_report
    )

    save_diagnosis(
        deviation_report,
        diagnoses
    )

    print_diagnosis(
        deviation_report,
        diagnoses
    )

    print()

    print(
        "Engineering diagnosis saved to:"
    )

    print(
        OUTPUT_FILE
    )

    print()


if __name__ == "__main__":
    main()