import json
import os


INPUT_FILE = "output/reference_measurements.json"


def load_measurements():
    """
    Load the measurements generated by reference_analyzer.py.
    """

    if not os.path.exists(INPUT_FILE):
        raise FileNotFoundError(
            f"Measurement file not found: {INPUT_FILE}"
        )

    with open(
        INPUT_FILE,
        "r",
        encoding="utf-8"
    ) as file:
        return json.load(file)


def validate_band_totals(measurements):
    """
    Check whether the eight relative spectral bands
    approximately sum to 100% for every reference.
    """

    print()
    print("========================================")
    print("BAND TOTAL VALIDATION")
    print("========================================")
    print()

    all_valid = True

    for measurement in measurements:

        file_name = measurement["file"]
        bands = measurement["bands"]

        total = sum(bands.values())

        difference = abs(100.0 - total)

        if difference <= 0.5:
            status = "PASS"
        else:
            status = "FAIL"
            all_valid = False

        print(
            f"{file_name:<30}"
            f" Total: {total:>7.2f}%"
            f"  Difference: {difference:>6.2f}%"
            f"  [{status}]"
        )

    print()

    return all_valid


def validate_band_presence(measurements):
    """
    Confirm that every expected frequency band exists.
    """

    expected_bands = {
        "sub",
        "bass",
        "low_mid",
        "mid",
        "upper_mid",
        "presence",
        "brilliance",
        "air"
    }

    print("========================================")
    print("BAND STRUCTURE VALIDATION")
    print("========================================")
    print()

    all_valid = True

    for measurement in measurements:

        file_name = measurement["file"]

        actual_bands = set(
            measurement["bands"].keys()
        )

        missing = expected_bands - actual_bands

        if missing:
            print(
                f"{file_name}: FAIL"
            )

            print(
                f"Missing bands: "
                f"{', '.join(sorted(missing))}"
            )

            all_valid = False

        else:
            print(
                f"{file_name}: PASS"
            )

    print()

    return all_valid


def validate_values(measurements):
    """
    Confirm that all relative-energy values are
    valid percentages.
    """

    print("========================================")
    print("VALUE VALIDATION")
    print("========================================")
    print()

    all_valid = True

    for measurement in measurements:

        file_name = measurement["file"]

        for band, value in (
            measurement["bands"].items()
        ):

            if value < 0 or value > 100:
                print(
                    f"{file_name}: FAIL"
                )

                print(
                    f"{band} = {value:.2f}%"
                )

                all_valid = False

    if all_valid:
        print(
            "All band values are between 0% and 100%."
        )

    print()

    return all_valid


def main():

    measurements = load_measurements()

    totals_valid = validate_band_totals(
        measurements
    )

    structure_valid = validate_band_presence(
        measurements
    )

    values_valid = validate_values(
        measurements
    )

    print("========================================")
    print("VALIDATION SUMMARY")
    print("========================================")
    print()

    if (
        totals_valid
        and structure_valid
        and values_valid
    ):
        print("REFERENCE PROFILE DATA: PASS")
    else:
        print("REFERENCE PROFILE DATA: FAIL")

    print()


if __name__ == "__main__":
    main()